### ISSUE TITLE
Wrong content type

### ISSUE THREAD

**Issue by jadolg** [decubba/exchange-rate-api#1]
When calling the API, the content-type header returns `content-type: application/octet-stream` instead of `content-type: application/json`.

The issue happens when using curl without extra headers and also when specifying `-H "Accept: application/json"`.

**Comment by manuelernestog** [comment]
Hi @jadolg thanks for reporting this. I had not realized since the response included the type `application/json` and the content type was correct locally because it was functioning as SSR, but when the deployment was static this was modified and this problem occurred.

This has already been solved in v2.

Thanks again!
